#DISPLAY CONSTANTS
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 576
LOGO_WIDTH = 500
LOGO_HEIGHT = 166
GENERAL_FONT_SIZE = 30
INFO_FONT_SIZE = 20
INFO_POS_X = 850

# GAME CONSTANTS
GRAVITY = 3
NEW_TUNNEL_POS = 500
TUNNELS_DISTANCE = 500
CROSS_SPACE = 150
SCORE_POS_X = 500
SCORE_POS_Y = 100

#TUNNELS
TUNNEL_IMG = 'img/tunnel.png'
ENTRY_TUNNEL_IMG = 'img/entry_tunnel.png'
MIN_TUNNEL_HEIGHT = 50
TUNNEL_START = 1024
TUNNEL_WIDTH = 70
ENTRY_TUNNEL_HEIGHT = 20
SPEED = 4

# BIRD
COLORS = ["blue", "red", "pink", "violet", "green", "yellow", "orange", "white", "black"]
NUM_COLORS = len(COLORS)
BIRD_POS_X = 150
BIRD_INI_POS_Y = 250
BIRD_WIDTH = 35
BIRD_HEIGHT = 25
BIRD_JUMP_DISTANCE = 60

# GENETIC ALGORITHM CONSTANTS
POPULATION = 20
SELECTION = 6
MUTATION_THRESHOLD = 0.02